[build]
  # Run your entire root build script (client + server packaging)
  command = "npm ci && npm run build"
  # Publish the folder that contains your index.html
  publish = "dist/public"

[[redirects]]
  # SPA fallback: serve index.html for every path
  from   = "/*"
  to     = "/index.html"
  status = 200
