# Tell Netlify how to build and where to publish
[build]
  command = "cd client && npm ci && npm run build"  # go into client and build
  publish = "client/dist"                         # publish the output folder

# SPA fallback: serve index.html for every path
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
