# Tell Netlify where to find and build your client app
[build]
  base    = "client"                   # the folder containing package.json
  command = "npm ci && npm run build"  # runs in client/
  publish = "dist"                     # Vite outputs to client/dist

# SPA fallback: serve index.html for every path
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
