[build]
  base    = "client"                  # work from client/
  command = "npm ci && npm run build" # install & build in client/
  publish = "dist"                    # publish client/dist

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
